### ISSUE TITLE
Integración del frontend generado por Solid React Application Generator.

### ISSUE THREAD

**Issue by rmonvfer** [Arquisoft/radarin_es4a#64]
¿Está ya probada la integración del proyecto React como acordamos en la última reunión?
He pensado que podríamos partir de ese código e ir modificandolo para añadir nuestras funcionalidades en lugar de empezar el desarrollo con el anterior.

**Comment by israelmnrg** [comment]
Exacto Ramón. Hemos comprobado que funciona perfectamente y vamos a empezar a realizar el mapa con la localización de nuestros amigos.
